language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: vPfZlxB254PWQdIW4NYZ6SJSVhbjcpzsHfvxv+GxUZyttGe8GJn7jshQRirg8Kl7Wz5EEfERLN9a3shPR47GY6cwJlYcDtFs02dYk3RymI7uu3RCX6VGLgZb3YVaXqBVLKouoGFhTGPh48PPYrIEah2ddGJ9Stt1CZORnq1WJ5PoFKqfCj35afx9skwsYH4MQX8vnMbEEDMf1sk2v0tMWVdREo2Dfd/0WAF+6hk7WRhd9N/3Q82YryRUB1CmOrimYBVizPRY1JgXtKz2C3WzexsWDVfst2VNtBgtpC5m20V/dzSig0cny0zAtU69hE0+HbBz8kZk0wgEs2pk0IOGOSHh+oTu3SYjlZ5P3WsAXmnJRKMQ0uDhExYpI1n16xCNG01PcPtZtoJHuvT9qWKbNs3pEZ9ezKBtIBQa3mfmLAnd73b1q2w91OuQ5jUSxY0oFQYREZZknEPPJxTOiU2/GuehvJzU7sPbCr9+xO0HzbNcxGrcw0aO4FRSL06A8MuSKBTQm45qk66scG+HnsPlFUIml32LDGmkeYpexJ3D0uxSA2J87oalJVHVFkOwaJmFZNZaa2e5w9k8+hDqgqHVSf3r16dsR92ADOyFlnFrJUks90zNJu1/EOscXPaJDvIGwMy5xVVAuCIfJKTdQdvaQte0wZoao1wQEtwuyCzGZB4=
