language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: tda6W3Vb/u+prYsyltJ1oCjLYEcedo3F3YzJhH0ZwQKN7Zp6iVl5zkhPeR05W2M3ZAtgDIsm/pGeyyc6Pc76WVyl7m+/+9i9J5hleT1Q60Mg0pJnw49/FISMy+yeavNmqFqt5HqXxyLzI/alQ0AW88TyxWCTyCvxgALc0lUEnpVXm5d945uP7Zb1IZ8HKQ6HP+a2Ce1oittdUpRTre51vXda0iMFhL/PS424TZEQvBd/HH+IBIpjwAMmgUqgTaiZ7QfphaMCP/2onscL1C/CHXZoN+Q9YllRQw7m7suhDYSxiNmpkhFnNJ2NIsIdoRWSQoF7ICNE8y111kyaZkviXLA2qLuRKPZUT2sIjXu5xP72AB1pNW15HwSRZX8XUuWgpWgiWX7WlBhHUO0IYTpnt15uT8ajK8mRWrdMIQHdVwJwtuQ6UXSbzgRkEDBsrIEqVXOw4cmQMchpl6h220tnsWoGTgWLYqic80DKuGMYk4JqP3i5qaKsL7mUsHnxmt2wI+sbKwxVBtsIm9/Yd045OjYaOdcWz/sDWzvbOswz+ki/2fI0PTHisNtwGTQlF/lJOFMPRiwpL/fU7eMWKwkaNYnOmNePSusLmqCMLp2vCO4JvjYr9jkeNvGxTG7pfpHySW/kYX0p18BNLVPQ7zzl7ArvGgxmAxnDF5jZ+Ik9cos=
  app: peaceful-beach-71190
