language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  app: peaceful-beach-71190
  api_key:
    secure: Isr8XdxCJWwNwCiXIoQM1+WLjq9w19m/UnUpKEovL2KwUTwm6ZY5jqeLgcVrcUKOA1qWjgJRTZRAqL4EHGjM8SsfiMsgAHRIKC/4W7ZveG4EUVvGQ+zvi4oHn2var9XCluAmi5+yZjv7KHySYZZj7RO628TDNDFzT9w1B3FnHH7L7HzfPxpmx8VW15STNb41RB/GWBvZXWyWuNyvhjOiiRLLlMCEKEd6/DUp8kllDDjrwOP2HnuhtGDIrrp979F3ROCQuWgfOcUJVh0ZOE+4ILNlQFdP+8W8xhrXPE9UlJljNS6gwhljK2wMKtImjDRdEY5Yc2p5xqsv9zN3C/uUMr35Rto2HWXjyr1HJEeEjxvm3Zk35/lBJx7iKdro+CGxhJ3+R6n6zLWDgF4U2JdInT1sKw9nKWcrXuBJI9dxPQM/zfZLrzWT5GoZmdXqFzJLM5+DubgEXAkCXTY/CdetjRcNr1f2sP0N0P6vhj9KOZqpSEBIkVaaWOnzeafp4l7MtL4V9iDYaXK4PnUKs8AU1HT7c2SmdzFUXj+w2qOZzhWXhmgLQxQS/7WNmyxveyEtNj77QYGez9O3wfy3xjPVYrtycJzmMi4DbgK8sX+ltOVcS3wN7zrh0IqEDVgSop+yWwgjOdHGtkfrOs/A4xVprQYl/9pdGPQGpDpmfWUIo80=
